name: IDAD

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled, closed]
  issue_comment:
    types: [created]

concurrency:
  group: idad-${{ github.event_name }}-${{ github.event.issue.number || github.event.pull_request.number }}
  cancel-in-progress: false

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write

env:
  # CLI selection: 'claude', 'cursor', or 'codex' (default: claude)
  IDAD_CLI: ${{ vars.IDAD_CLI || 'claude' }}

  # Model configuration (users set these with CLI-appropriate names)
  MODEL_DEFAULT: ${{ vars.IDAD_MODEL_DEFAULT || '' }}
  MODEL_PLANNER: ${{ vars.IDAD_MODEL_PLANNER || '' }}
  MODEL_IMPLEMENTER: ${{ vars.IDAD_MODEL_IMPLEMENTER || '' }}
  MODEL_REVIEWER: ${{ vars.IDAD_MODEL_REVIEWER || '' }}
  MODEL_SECURITY: ${{ vars.IDAD_MODEL_SECURITY || '' }}
  MODEL_DOCUMENTER: ${{ vars.IDAD_MODEL_DOCUMENTER || '' }}
  MODEL_ISSUE_REVIEW: ${{ vars.IDAD_MODEL_ISSUE_REVIEW || '' }}
  MODEL_IDAD: ${{ vars.IDAD_MODEL_IDAD || '' }}

jobs:
  # ======================
  # ROUTER
  # ======================
  router:
    runs-on: ubuntu-latest
    outputs:
      agent: ${{ steps.route.outputs.agent }}
      model: ${{ steps.route.outputs.model }}
      issue: ${{ steps.route.outputs.issue }}
      pr: ${{ steps.route.outputs.pr }}
      skip: ${{ steps.route.outputs.skip }}
      message: ${{ steps.route.outputs.message }}
    steps:
      - id: route
        uses: actions/github-script@v7
        env:
          MODEL_DEFAULT: ${{ env.MODEL_DEFAULT }}
          MODEL_PLANNER: ${{ env.MODEL_PLANNER }}
          MODEL_IMPLEMENTER: ${{ env.MODEL_IMPLEMENTER }}
          MODEL_REVIEWER: ${{ env.MODEL_REVIEWER }}
          MODEL_SECURITY: ${{ env.MODEL_SECURITY }}
          MODEL_DOCUMENTER: ${{ env.MODEL_DOCUMENTER }}
          MODEL_ISSUE_REVIEW: ${{ env.MODEL_ISSUE_REVIEW }}
          MODEL_IDAD: ${{ env.MODEL_IDAD }}
        with:
          script: |
            const { eventName, payload } = context;
            const action = payload.action;

            // Model mapping
            const models = {
              'issue-review': process.env.MODEL_ISSUE_REVIEW,
              'planner': process.env.MODEL_PLANNER,
              'implementer': process.env.MODEL_IMPLEMENTER,
              'security-scanner': process.env.MODEL_SECURITY,
              'reviewer': process.env.MODEL_REVIEWER,
              'documenter': process.env.MODEL_DOCUMENTER,
              'idad': process.env.MODEL_IDAD,
            };

            // Label to agent mapping (only ONE idad:* label at a time)
            const labelToAgent = {
              'idad:issue-review': 'issue-review',
              'idad:planning': 'planner',
              'idad:implementing': 'implementer',
              'idad:security-scan': 'security-scanner',
              'idad:code-review': 'reviewer',
              'idad:documenting': 'documenter',
            };

            // Human review states (no agent, just log)
            const humanStates = {
              'idad:issue-needs-clarification': 'â“ Issue needs clarification. Please answer the questions and comment.',
              'idad:human-plan-review': 'ðŸ“‹ Awaiting human plan review. Comment to provide feedback or approve.',
              'idad:human-pr-review': 'âœ… Ready for human review and merge.',
            };

            let agent = '';
            let issue = '';
            let pr = '';
            let skip = false;
            let message = '';

            const getLabels = (obj) => obj?.labels?.map(l => l.name) || [];
            const hasLabel = (labels, name) => labels.includes(name);

            // === ISSUE LABELED ===
            if (eventName === 'issues' && action === 'labeled') {
              const labelName = payload.label?.name || '';
              issue = String(payload.issue.number);

              if (labelToAgent[labelName]) {
                agent = labelToAgent[labelName];
              } else if (humanStates[labelName]) {
                message = humanStates[labelName];
                skip = true;
              } else {
                skip = true;
              }
            }

            // === PR LABELED ===
            else if (eventName === 'pull_request' && action === 'labeled') {
              const labelName = payload.label?.name || '';
              pr = String(payload.pull_request.number);

              if (labelToAgent[labelName]) {
                agent = labelToAgent[labelName];
              } else if (humanStates[labelName]) {
                message = humanStates[labelName];
                skip = true;
              } else {
                skip = true;
              }
            }

            // === PR MERGED (triggers IDAD agent) ===
            else if (eventName === 'pull_request' && action === 'closed') {
              const prData = payload.pull_request;
              const branch = prData.head?.ref || '';

              if (prData.merged && !branch.startsWith('idad/')) {
                agent = 'idad';
                pr = String(prData.number);
              } else {
                skip = true;
              }
            }

            // === COMMENT EVENTS ===
            else if (eventName === 'issue_comment' && action === 'created') {
              const commenter = payload.comment?.user?.login || '';
              const isPrComment = !!payload.issue?.pull_request;
              const labels = getLabels(payload.issue);
              const number = String(payload.issue.number);

              if (commenter.includes('[bot]')) {
                console.log('â­ï¸ Skipping bot comment');
                skip = true;
              }
              else if (!isPrComment && hasLabel(labels, 'idad:issue-needs-clarification')) {
                agent = 'issue-review';
                issue = number;
              }
              else if (!isPrComment && hasLabel(labels, 'idad:human-plan-review')) {
                agent = 'planner';
                issue = number;
              }
              else if (isPrComment && hasLabel(labels, 'idad:human-pr-review')) {
                agent = 'implementer';
                pr = number;
              }
              else {
                skip = true;
              }
            }

            else {
              skip = true;
            }

            const model = models[agent] || process.env.MODEL_DEFAULT;

            core.setOutput('agent', agent);
            core.setOutput('model', model);
            core.setOutput('issue', issue);
            core.setOutput('pr', pr);
            core.setOutput('skip', String(skip));
            core.setOutput('message', message);

            console.log(`ðŸš¦ Router: agent=${agent}, issue=${issue}, pr=${pr}, model=${model}, skip=${skip}`);
            if (message) console.log(`ðŸ“ ${message}`);

  # ======================
  # AGENT
  # ======================
  agent:
    needs: router
    runs-on: ubuntu-latest
    if: needs.router.outputs.skip != 'true' && needs.router.outputs.agent != ''
    steps:
      - name: Get IDAD GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.IDAD_APP_ID }}
          private-key: ${{ secrets.IDAD_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Run ${{ needs.router.outputs.agent }} agent
        uses: ./.github/actions/run-idad-agent
        with:
          cli: ${{ env.IDAD_CLI }}
          agent: ${{ needs.router.outputs.agent }}
          model: ${{ needs.router.outputs.model }}
          issue: ${{ needs.router.outputs.issue }}
          pr: ${{ needs.router.outputs.pr }}
          repo: ${{ github.repository }}
          run-id: ${{ github.run_id }}
          github-token: ${{ steps.app-token.outputs.token }}
          # Claude Code auth (supports both API key and OAuth token)
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          anthropic-auth-token: ${{ secrets.ANTHROPIC_AUTH_TOKEN }}
          # Cursor auth
          cursor-api-key: ${{ secrets.CURSOR_API_KEY }}
          # Codex auth
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}

  # ======================
  # SUMMARY (for human states)
  # ======================
  summary:
    needs: router
    runs-on: ubuntu-latest
    if: needs.router.outputs.message != ''
    steps:
      - name: Log human review state
        run: |
          echo "${{ needs.router.outputs.message }}"
          echo "## IDAD Status" >> $GITHUB_STEP_SUMMARY
          echo "${{ needs.router.outputs.message }}" >> $GITHUB_STEP_SUMMARY
